# примеры API-запросов

@baseUrl = http://localhost:8080/weather/
@token = 70a879f6fcbeb53066986e11c82bc74a

### Получить прогноз (POST)
POST {{baseUrl}}
Content-Type: application/json

{
  "city": "Москва",
  "token": "{{token}}"
}
